### PR TITLE
Fix app icon on Wayland

### PR DESCRIPTION
**Pull request by OlegAckbar**
Right now, application icon on Wayland could only be changed by setting application ID that is corresponding to the name of desktop entry. https://wayland.app/protocols/xdg-shell#xdg_toplevel:request:set_app_id

| Before | After |
|--------|--------|
| Снимок экрана_20241116_140354| Снимок экрана_20241116_141546 |

### CODE REVIEW

**Comment by mtkennerly** [comment]
Hi! Are you using Flatpak? I thought this should be handled by the couple of lines here:

https://github.com/flathub/com.github.mtkennerly.ludusavi/blob/a19e036d262a955c5ca601f6477f875441f469f2/com.github.mtkennerly.ludusavi.yaml#L47-L48

If you're using the standalone executable, can you call the desktop file `ludusavi.desktop`? Or perhaps are you using some distro-specific package?

I wouldn't be opposed to adding support for a `LUDUSAVI_LINUX_APP_ID` environment variable if needed, but I'd like to understand your situation a bit better :)

**Comment by OlegAckbar** [comment]
I'm using a standalone executable from AUR

> If you're using the standalone executable, can you call the desktop file ludusavi.desktop?

This contradicts [freedesktop desktop entry spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/file-naming.html)

> The name of the desktop entry should follow the "reverse DNS" convention: it should start with a reversed DNS domain name controlled by the author of the application, in lower case. The domain name should be followed by the name of the application, which is conventionally written with words run together and initial capital letters (CamelCase). For example, if the owner of example.org writes "Foo Viewer", they might choose the name org.example.FooViewer, resulting in a file named org.example.FooViewer.desktop.

**Comment by OlegAckbar** [comment]
> I wouldn't be opposed to adding support for a LUDUSAVI_LINUX_APP_ID environment 
There's no need for an environment variable for that. The right and only way to set an application icon on Wayland is to set the proper application id which corresponds to its desktop entry which in turn follows the desktop entry specification. This is how all Wayland applications are made.

**Comment by mtkennerly** [comment]
Thanks, that makes sense. I knew that Flatpak apps followed that kind of naming convention, but I didn't realize that it was a broader standard.

When the Flatpak app ID was created as `com.github.mtkennerly.ludusavi`, Flatpak didn't yet enforce its [current guidance](https://docs.flatpak.org/en/latest/conventions.html#application-ids) to avoid `com.github` since technically the project only has control over `io.github`. I think it's too late to fix the Flatpak ID (unless Flatpak can eventually support some automatic migration for users from an old ID to a new ID), but I think this is a good opportunity to use a better ID elsewhere.

I've just registered mtkennerly.com (although it's not hosting anything yet), so we can use `com.mtkennerly.ludusavi` for the ID, if you could update the PR.

I don't maintain the distro packages myself, but I do see that both of the AUR packages ([ludusavi](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ludusavi) and [ludusavi-bin](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ludusavi-bin)) set the ID to `com.github.mtkennerly.ludusavi`. I can try to reach out to their maintainers before the next Ludusavi release so they can update the ID on their end.

Besides setting the ID in the Rust code, I think we'll need to make some other changes. I can do these after this merges, but just wanted to bring it up in case you have any feedback/advice:

* Replace `assets/ludusavi.desktop` with two files:
  * For Flatpak, `assets/com.github.mtkennerly.ludusavi.desktop` with `Icon=com.github.mtkennerly.ludusavi`
  * For other contexts, `assets/com.mtkennerly.ludusavi.desktop` with `Icon=com.mtkennerly.ludusavi`
* Keep `assets/com.github.mtkennerly.ludusavi.metainfo.xml` for Flatpak, but make a copy named `assets/com.mtkennerly.ludusavi.metainfo.xml` that replaces the app ID in the `<id>` and `launchable` tags
* For Flatpak to set its app ID, the Flatpak `finish-args` can set something like `--env=LUDUSAVI_LINUX_APP_ID=com.github.mtkennerly.ludusavi`

**Comment by OlegAckbar** [comment]
Having two different ID doesn't make much sense. If there's already established ID for Flatpak I think we should use it, making a separate ID for regular use would just create more chaos.
I've updated desktop entry correspondingly.

**Pull request merged**
